### ISSUE TITLE
This should be a VS Code plugin!

### ISSUE THREAD

**Issue by Eclmist** [Wooniety/Messing-with-VS-Code#1]
Copy and pasting is too much hassle, why not write it as an extension so that all you would need to do is install this extension on someone's machine? ;)

**Comment by Wooniety** [comment]
In place of Donut Lord emails? LOL

**Comment by Wooniety** [comment]
It has been done :D 

You can find the extension [here](https://marketplace.visualstudio.com/items?itemName=Wooniety.Colour-Theme-Nuke), or look up Donut Lord in the marketplace!
